// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCNaqdOznQrrFic_xDHxuAlAwiR6oOSgk',
    appId: '1:416392219996:web:641b94fb9332102f7ec599',
    messagingSenderId: '416392219996',
    projectId: 'e-commerce2-8d22d',
    authDomain: 'e-commerce2-8d22d.firebaseapp.com',
    storageBucket: 'e-commerce2-8d22d.appspot.com',
    measurementId: 'G-RKNHL3M8F2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoM0guoMSX-6fqnHkbE9HYDaGIFRRllc0',
    appId: '1:416392219996:android:d4e0fa89855e891b7ec599',
    messagingSenderId: '416392219996',
    projectId: 'e-commerce2-8d22d',
    storageBucket: 'e-commerce2-8d22d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWDkgIEj4LkwPwVvkGnE-B1TvZdJRHADk',
    appId: '1:416392219996:ios:2867b54ba173d1337ec599',
    messagingSenderId: '416392219996',
    projectId: 'e-commerce2-8d22d',
    storageBucket: 'e-commerce2-8d22d.appspot.com',
    iosClientId: '416392219996-bvcinhek3sqroe1ph1g4k8mq0gqdrie8.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWDkgIEj4LkwPwVvkGnE-B1TvZdJRHADk',
    appId: '1:416392219996:ios:2867b54ba173d1337ec599',
    messagingSenderId: '416392219996',
    projectId: 'e-commerce2-8d22d',
    storageBucket: 'e-commerce2-8d22d.appspot.com',
    iosClientId: '416392219996-bvcinhek3sqroe1ph1g4k8mq0gqdrie8.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );
}
